name: Keep the app awake

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */10 * * *' # runs every 10 hours

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: push empty commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit --alow-empty -m "keep-alive ping"
          git push